[theme]
primaryColor = "#2a2a2a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f8f8"
textColor = "#2a2a2a"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false